# Generated by Django 4.2.1 on 2023-05-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kersus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Categories'},
        ),
    ]
